name: Create tag

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release/**

jobs:
  create-tag:
    if: ${{ vars.CREATE_TAGS }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all tags
          fetch-depth: 0
          submodules: true

      - name: Read version file
        run: echo "CURRENT_VERSION=$(cat odin/VERSION)" >> $GITHUB_ENV

      - name: Set stage to snapshot
        if: ${{ !startsWith(github.ref, 'refs/heads/release') }}
        run: echo "OVERRIDE_STAGE=snapshot" >> $GITHUB_ENV

      - name: Get next snapshot version
        id: next-version
        if: ${{ !startsWith(github.ref, 'refs/heads/release') }}
        uses: symless/actions/next-version@master
        with:
          current-version: ${{ env.CURRENT_VERSION }}
          override-stage: ${{ env.OVERRIDE_STAGE }}

      - name: Create and push Git tag
        run: |
          git tag ${{ steps.next-version.outputs.next-version }}
          git push origin ${{ steps.next-version.outputs.next-version }}
        shell: bash

      - name: Trigger CI workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: '${{ steps.next-version.outputs.next-version }}'
            });
